---
deployment:
  tasks:
    - export DEPLOYPATH=/home/color160/public_html/
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp latest-news.html $DEPLOYPATH
    - /bin/cp meetings.html $DEPLOYPATH
    - /bin/cp playlists.html $DEPLOYPATH
    - /bin/cp upcomingEvents.html $DEPLOYPATH
    - /bin/cp -r styles $DEPLOYPATH
    - /bin/cp -r scripts $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH


